  var titles = [
   'i would love some milk',
   'hi',
   'milk',
   '<3',
   '#ilikemilk',
   'i am a cow',
   'moo',
   'milk is love, milk is life',
   'tf is this ai suggesting💀💀',
   'john pork',
   'wts amogus prime chasis 20p',
   'beatbanger is a REAL banger frfr',
   'js sucks(offensive)',
   'ttv/londik_',
   'sixsayven',
   'x gon give it to ya',
   'ts has a LOT of possible names',
   'god i love BILILI',
   'hop on hunt showdown',
   'localhost:5500',
   '4daboyz',
   'guns.lol, so fckn childish jeez',
   'its actually random',
   'gayest-porn.now',
   'go and hug ur mother',
   'its @londi_ or @londik at anywhere',
   'halo everynyan',
   'cherry is my luv. -anon',
   'dornerhek is my luv. -anon',
   'misheez is my luv. -anon',
   'oguzok is my luv. -anon',
   'this site is 0% ai. no fake',
   'footer is actually a steam link',
   'i love lua',
   '😂 u can put emojis here wtf',
   'did ya find em all?',
   'i miss the fireflies',
   'root@vps-1337'
]
  var title = titles[Math.floor(Math.random() * titles.length)] // why are u actually lookin' here?...
  document.title = title